# Generated by Django 2.1.7 on 2019-04-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=12)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
