version: '3'

volumes:
  pgdata:

services:

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

  timescale:
    image: timescale/timescaledb-postgis:latest-pg11
    ports:
      - "15432:15432"
    build:
      context: .
      args:
        - db_name=canairio
      dockerfile: Dockerfile_timescaledb
    environment:
      - POSTGRES_USER=canairio
      - POSTGRES_PASSWORD=canairio
      - POSTGRES_DB=canairio
      - POSTGRES_TEST_DB=canairio_test

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'canairio_user'
      POSTGRES_PASSWORD: 'canairio_password'
      POSTGRES_DB: 'canairio'
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: ./start
    volumes:
      - .:/canairio
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - timescale
      - db
    links:
      - influxdb
      - timescale
    environment:
      - DJANGO_SETTINGS_MODULE=canairio.settings.development
      - DATABASE_URL=postgresql://canairio_user:canairio_password@db/canairio
      - DATABASE_NAME=canairio
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DATABASE=canairio
      - ENVIRONMENT=development
      - SECRET_KEY=so_secret
