#!/bin/sh
pip install -r requirements.txt
influx -host $INFLUXDB_HOST -precision rfc3339 -execute 'CREATE DATABASE '$INFLUXDB_DATABASE
python manage.py migrate

while [ 1 ]; do
    date
    sleep 30
done
