"""
Django settings for canairio project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import django_heroku
import os
from dj_database_url import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from datetime import timedelta

ENVIRONMENT = 'development'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(e7f8&@wbya^bm7km^&-bd9-!0oqb3u*^62wq^3*9gqsoki#7!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['gblabs.co']

CORS_ORIGIN_WHITELIST = ['canairiofront.herokuapp.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'knox',
    'users',
    'tracks',
    'points',
    'corsheaders',
    'drf_yasg'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'canairio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'canairio.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'knox.auth.TokenAuthentication',
    )
}

TRACK_COLLECTION_NAME = 'test_tracks_data'

FB_API_KEY = os.getenv('FB_API_KEY', '')
FB_AUTH_DOMAIN = os.getenv('FB_AUTH_DOMAIN', '')
FB_DATABASE_URL = os.getenv('FB_DATABASE_URL', '')
FB_STORAGE_BUCKET = os.getenv('FB_STORAGE_BUCKET', '')

INFLUXDB_HOST = os.getenv('INFLUXDB_HOST', '')
INFLUXDB_PORT = 8086
INFLUXDB_USERNAME = None
INFLUXDB_PASSWORD = None
INFLUXDB_DATABASE = 'canairio'
INFLUXDB_TIMEOUT = 10

ENVIRONMENT = os.getenv('ENVIRONMENT', ENVIRONMENT)
if 'production' in ENVIRONMENT:


    FB_API_KEY = os.getenv('FB_API_KEY', '')
    FB_AUTH_DOMAIN = os.getenv('FB_AUTH_DOMAIN', '')
    FB_DATABASE_URL = os.getenv('FB_DATABASE_URL', '')
    FB_STORAGE_BUCKET = os.getenv('FB_STORAGE_BUCKET', '')

    INFLUXDB_HOST = os.getenv('INFLUXDB_HOST', '')
    INFLUXDB_PORT = 8086
    INFLUXDB_USERNAME = None
    INFLUXDB_PASSWORD = None
    INFLUXDB_DATABASE = os.getenv('INFLUXDB_DATABASE', '')
    INFLUXDB_TIMEOUT = 10

    DATABASES = {
        'default': config(
            default=config('DATABASE_URL')
        )
    }

else:
    try:
        from canairio.settings_local import *
    except ImportError:
        print('You must create a settings_local.py file.')

django_heroku.settings(locals())

if 'CIRCLE_ENV' in os.environ:
    del DATABASES['default']['OPTIONS']['sslmode']
